PDB=$1
SURF=$2

echo "computePotential ON"
echo "computeEnergy ON"
echo "computeVolumePotential ON"
echo "computeForces OFF"
echo "pqrFile PQR/${PDB}.pqr"
echo "rawnFile RAWN/${SURF}.rawn"
echo "potentialFile PBOUT256/${PDB}.potential"
echo "outputPrefix PBOUT256/${PDB}"
echo "ionConc 0.0"
echo "epsilonE 80"
echo "epsilonI 2"
echo "temperature 300"
echo "linearSolver GMRES"
echo "discretizationMethod Collocation"
echo "bieFormulation DBIE"
echo "geometry ASpline"
echo "quadratureLevel 1"
echo "quadOrderFarField 3"
echo "quadOrderNearField 1"
echo "quadOrderSingular 3"
echo "fmmAccuracy 4"
echo "solvationVolumePotentialOnly 0"
#echo "sdfFile RAWIV/sdf_${PDB}.rawiv"
echo "rawivOutputResolution 128"
